export const rochas = [
  'Calcário - Mohs 3',
  'Calcário dolomítico - Mohs 3.8',
  'Calcário micrítico - Mohs 3',
  'Calcário oolítico - Mohs 3',
  'Travertino - Mohs 3',
  'Calcilutito - Mohs 3',
  'Calcarenito - Mohs 3.2',
  'Calcirrudito - Mohs 3.2',
  'Dolomita - Mohs 3.8',
  'Marga - Mohs 3',
  'Gesso - Mohs 2',
  'Anidrita - Mohs 3',
  'Halita (sal-gema) - Mohs 2.5',
  'Evaporito (misto) - Mohs 2.5',
  'Fosforito - Mohs 5',
  'Diatomito - Mohs 3.5',
  'Carvão betuminoso - Mohs 2.5',
  'Antracito - Mohs 3',
  'Arenito - Mohs 6.5',
  'Arenito quartzoso - Mohs 6.8',
  'Arenito feldspático (arcoseano) - Mohs 6.2',
  'Arenito lítico - Mohs 6',
  'Arenito ferruginoso - Mohs 6.8',
  'Arenito glauconítico - Mohs 6.2',
  'Arenito silicificado - Mohs 7',
  'Arenito argiloso - Mohs 5.5',
  'Arenito conglomerático - Mohs 6.5',
  'Siltito - Mohs 3.5',
  'Folhelho - Mohs 3',
  'Folhelho betuminoso - Mohs 3',
  'Lutito - Mohs 3',
  'Argilito - Mohs 2.8',
  'Conglomerado (matriz argilosa) - Mohs 5.5',
  'Conglomerado (matriz sílica) - Mohs 6.8',
  'Brecha sedimentar - Mohs 6',
  'Varvito (ritmito) - Mohs 3.3',
  'Laterita - Mohs 5.5',
  'Canga (latossolo endurecido) - Mohs 5.8',
  'Ferricrete - Mohs 6',
  'BIF (Formação Ferrífera Bandada) - Mohs 6.8',
  'Itabirito - Mohs 6.8',
  'Hematitito compacto - Mohs 6.5',
  'Jaspelito - Mohs 6.8',
  'Chert - Mohs 7',
  'Sílex - Mohs 7',
  'Calcedônia - Mohs 6.8',
  'Opala (comum) - Mohs 5.5',
  'Silexito - Mohs 7',
  'Tufito carbonático - Mohs 3',
  'Tufo calcário - Mohs 3',
  'Caliche - Mohs 3',
  'Basalto - Mohs 6',
  'Basalto vesicular - Mohs 6',
  'Basalto amigdaloidal - Mohs 6',
  'Basalto porfirítico - Mohs 6.2',
  'Basalto alterado - Mohs 5.5',
  'Diabásio - Mohs 6.5',
  'Andesito - Mohs 6.5',
  'Andesito porfirítico - Mohs 6.6',
  'Andesito vesicular - Mohs 6.2',
  'Riolito - Mohs 6',
  'Riolito porfirítico - Mohs 6.2',
  'Dacito - Mohs 6.5',
  'Traquito - Mohs 6',
  'Fonolito - Mohs 5.8',
  'Tephri-fonolito - Mohs 5.8',
  'Traquiandesito - Mohs 6.2',
  'Ignimbrito soldado - Mohs 6',
  'Ignimbrito não soldado - Mohs 5.5',
  'Tufo vulcânico - Mohs 5.5',
  'Brecha vulcânica - Mohs 6',
  'Tefra consolidada - Mohs 5.5',
  'Obsidiana - Mohs 5.5',
  'Pumita (pumice) - Mohs 5.5',
  'Escória basáltica - Mohs 5.8',
  'Komatito - Mohs 6',
  'Kimberlito - Mohs 6',
  'Carbonatito - Mohs 3.5',
  'Gabro - Mohs 6.5',
  'Norito - Mohs 6.5',
  'Anortosito - Mohs 6',
  'Peridotito - Mohs 6.5',
  'Dunito - Mohs 6.5',
  'Harzburgito - Mohs 6.5',
  'Lherzolito - Mohs 6.5',
  'Sienito - Mohs 5.8',
  'Sienito nefelínico - Mohs 5.8',
  'Foiaíto - Mohs 5.8',
  'Monzonito - Mohs 6',
  'Monzodiorito - Mohs 6.2',
  'Diorito - Mohs 6.5',
  'Quartzo-diorito - Mohs 6.5',
  'Granodiorito - Mohs 6.5',
  'Granito - Mohs 6.5',
  'Monzogranito - Mohs 6.5',
  'Sienogranito - Mohs 6.5',
  'Tonalito - Mohs 6.5',
  'Pegmatito - Mohs 6.5',
  'Aplito - Mohs 6.5',
  'Charnockito - Mohs 6.5',
  'Quartzito - Mohs 7',
  'Quartzito micáceo - Mohs 6.8',
  'Quartzito ferruginoso - Mohs 6.9',
  'Gnaisse - Mohs 6.5',
  'Gnaisse bandado - Mohs 6.6',
  'Gnaisse granítico - Mohs 6.5',
  'Gnaisse charnockítico - Mohs 6.6',
  'Migmatito - Mohs 6.5',
  'Milonito - Mohs 6.2',
  'Cataclasito - Mohs 6',
  'Tectonito - Mohs 6.5',
  'Xisto (biotita) - Mohs 4.8',
  'Xisto (clorita) - Mohs 4.2',
  'Xisto (muscovita) - Mohs 4.5',
  'Xisto grafitoso - Mohs 4',
  'Filito - Mohs 3.5',
  'Ardósia - Mohs 4',
  'Mármore - Mohs 3.5',
  'Mármore dolomítico - Mohs 3.8',
  'Serpentinitos - Mohs 3.5',
  'Talco-xisto - Mohs 2',
  'Cloritito - Mohs 3',
  'Anfibolito - Mohs 5.8',
  'Eclogito - Mohs 7.5',
  'Hornfels - Mohs 6',
  'Skarn (calcossilicatado) - Mohs 6.5',
  'Metabasito - Mohs 6.2',
  'Metagabro - Mohs 6.3',
  'Metagranito - Mohs 6.5',
  'Meta-arenito - Mohs 6.8',
  'Meta-argilito - Mohs 3.2',
  'Meta-limestone - Mohs 3.5',
  'Quartzito cataclástico - Mohs 7',
  'Quartzo milonítico - Mohs 7',
  'Xisto anfibolítico - Mohs 5.8',
  'Gnaisse milonítico - Mohs 6.4',
  'Mármores impuros (silicosos) - Mohs 4',
  'Veio de quartzo - Mohs 7',
  'Brecha hidrotermal - Mohs 6.5',
  'Silcrete - Mohs 7',
  'Ferruginização (boxwork) - Mohs 6.5',
  'Argilização intensa - Mohs 2.8',
  'Caulinita (rocha caulinizada) - Mohs 2.5',
  'Lateritização níquel - Mohs 5.5',
  'Gossan - Mohs 5.5',
  'Greisen - Mohs 6.5',
  'Zonas talcose - Mohs 2',
  'Saprolito granítico - Mohs 3.5',
  'Saprolito basáltico - Mohs 3.5',
  'Saprolito gnáissico - Mohs 3.8',
]
